# Import Libraries:

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

# Example Sentences:

In [3]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size=10000

# One Hot Representation:

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[1991, 8531, 9656, 1955], [1991, 8531, 9656, 2597], [1991, 4514, 9656, 3480], [9575, 2674, 9499, 6597, 7906], [9575, 2674, 9499, 6597, 5636], [1596, 1991, 2951, 9656, 9331], [6541, 2569, 1200, 6597]]


# Word Embedding Represntation:

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1991 8531 9656 1955]
 [   0    0    0    0 1991 8531 9656 2597]
 [   0    0    0    0 1991 4514 9656 3480]
 [   0    0    0 9575 2674 9499 6597 7906]
 [   0    0    0 9575 2674 9499 6597 5636]
 [   0    0    0 1596 1991 2951 9656 9331]
 [   0    0    0    0 6541 2569 1200 6597]]


In [ ]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 853ms/step
[[[ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666
    0.02384898  0.0129309  -0.01729172  0.02000076  0.02883078]
  [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666
    0.02384898  0.0129309  -0.01729172  0.02000076  0.02883078]
  [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666
    0.02384898  0.0129309  -0.01729172  0.02000076  0.02883078]
  [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666
    0.02384898  0.0129309  -0.01729172  0.02000076  0.02883078]
  [ 0.04352725  0.03195362  0.038833   -0.04653108 -0.04205142
    0.0226163  -0.04815943  0.01926256 -0.02042737  0.03816384]
  [-0.00931768 -0.02582952  0.02825158  0.0313665  -0.04461929
   -0.01834197 -0.03919192 -0.02911728  0.01690456  0.00104905]
  [ 0.03813268 -0.02808614  0.02582426 -0.04134878  0.03578054
    0.00663354  0.00654622 -0.02323673  0.03522522  0.04038114]
  [-0.00661641  0.04643271 -0.0469542  -0.03995813  0.04558721
    0.033

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1991, 8531, 9656, 1955], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666  0.02384898
   0.0129309  -0.01729172  0.02000076  0.02883078]
 [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666  0.02384898
   0.0129309  -0.01729172  0.02000076  0.02883078]
 [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666  0.02384898
   0.0129309  -0.01729172  0.02000076  0.02883078]
 [ 0.02783399 -0.02538009  0.02029132 -0.00217564  0.00613666  0.02384898
   0.0129309  -0.01729172  0.02000076  0.02883078]
 [ 0.04352725  0.03195362  0.038833   -0.04653108 -0.04205142  0.0226163
  -0.04815943  0.01926256 -0.02042737  0.03816384]
 [-0.00931768 -0.02582952  0.02825158  0.0313665  -0.04461929 -0.01834197
  -0.03919192 -0.02911728  0.01690456  0.00104905]
 [ 0.03813268 -0.02808614  0.02582426 -0.04134878  0.03578054  0.00663354
   0.00654622 -0.02323673  0.03522522  0.04038114]
 [-0.00661641  0.04643271 -0.0469542  -0.03995813  0.04558721  0.03373336
  -0.0118983  